{% set name = "prms" %}
{% set version = "6.0.0" %}
{% set release = "alpha" %}
{% set build_number = "7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/rmcd-mscb/{{ name }}
  git_rev: 6b1fe6584669ddf8740ca39fbb46405428601fb6

build:
  string: {{ release }}_{{ build_number }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}
    - libnetcdf
    - netcdf-fortran
  host:
    - libnetcdf
    - netcdf-fortran
    - coretran
  run:
    - libnetcdf
    - netcdf-fortran
    - coretran

test:
  commands:
    - prms

about:
  home: https://www.usgs.gov/software/precipitation-runoff-modeling-system-prms
  license: MIT
  license_file: LICENSE.md
  summary: The USGS Precipitation Runoff Modeling System
  description: |
    The Precipitation-Runoff Modeling System (PRMS) is a
    deterministic, distributed-parameter, physical process based
    modeling system developed to evaluate the response of various
    combinations of climate and land use on streamflow and general
    watershed hydrology.
  dev_url: https://github.com/nhm-usgs/prms
