language: generic

os:
  - linux
  - osx

env:
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
    - TRAVIS_PYTHON_VERSION="3.*"
    - secure: "R0i/csWywP+p91DIU1AY8bn4jQAAk2kVV0rP1zXlKbj2s0uKdKhzt67q6xrWCD8ea2YnpRXV9FXKcRDNHbrqh9W+3iQfGYUuKSPj3gXX1bLwyDaRucG+nm7pZjFEFYtaUCdqPyarj1/TExZXUjoU2buuwdEhIL+/xY4NhcnoGrOXOfenDT2YD6MN1t0iAqO9Cru+fOJYc7Wmtw0Id59QOqs6HptyumNtPdzHXh1Fqcah3J/7FAvCmrgKcbgaTJpyzT3vmXWtKRjagTPAh0wx8y/OXJ5k25l3Eg58iEDaWy5CQQ1humGCxxRem+47ra6mXWxWZkJA9WPqoiFQHJgtxJBpfLyWvCyIWZtzMsXrKjl0eWSOtTa4YCpqvKfSQj1hd9r3TfXo7AImTJJuoYqBQeSM6eTxhnOAnyS07CsV+IaLcO447TI4PHppl1FxfEYRzetfD9afQOt7jskPHg188FHLcNeMXBgMNMx5oVUJglxdYktzdZErAKSPzeUXoG1mkzU3s5orBipcWfdoH4DsJF0Ytsgi/CWTJFOsqpJU85yfNY9KMIMLo3cDG8xeEor635kS3z2kYMAFkQBkUwclosrWPZozgV74BAhzIHeKoKLMnlTuGBwXLk0qV5rkYa6H/B3mcNrzVdmKCFhjtugtpcR7BR4iUG8Xq2kUP8Hoqgg="

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install python=$TRAVIS_PYTHON_VERSION -c conda-forge
  - conda install -q conda-build anaconda-client -c conda-forge

script:
  - conda build ./recipe -c conda-forge -c csdms-stack --old-build-string

after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
